# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.runs/synth_1/SoC_EV_BD_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
set_msg_config  -id {17-179}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.cache/wt [current_project]
set_property parent.project_path /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/wonhyeok/.Xilinx/Vivado/2025.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/wonhyeok/ip_repo/CustomIP_TIMER_SEC_1_0
  /home/wonhyeok/ip_repo/CustomIP_EXTERNAL_FND_CNTR_1_0
  /home/wonhyeok/ip_repo/CustomIP_EXTERNAL_LED_CNTR_1_0
  /home/wonhyeok/ip_repo/CustomIP_PWM_1_0
  /home/wonhyeok/ip_repo/CustomIP_PHOTO_INT_CNTR_1_0
  /home/wonhyeok/ip_repo/CustomIP_EXTERNAL_BTN_CNTR_1_0
  /home/wonhyeok/ip_repo/CustomIP_STEPPER_1_0
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/hdl/SoC_EV_BD_wrapper.v
add_files /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.srcs/sources_1/bd/SoC_EV_BD/SoC_EV_BD.bd
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_proc_sys_reset_0_0/SoC_EV_BD_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_clk_wiz_0/SoC_EV_BD_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_clk_wiz_0/SoC_EV_BD_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_clk_wiz_0/SoC_EV_BD_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_microblaze_riscv_0_0/SoC_EV_BD_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_microblaze_riscv_0_0/SoC_EV_BD_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_lmb_bram_0/SoC_EV_BD_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_mdm_1_0/SoC_EV_BD_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_mdm_1_0/SoC_EV_BD_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_uartlite_0_0/SoC_EV_BD_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_uartlite_0_0/SoC_EV_BD_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_1/bd_cb0a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_2/bd_cb0a_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_3/bd_cb0a_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_4/bd_cb0a_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_5/bd_cb0a_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_6/bd_cb0a_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_7/bd_cb0a_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_8/bd_cb0a_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_9/bd_cb0a_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_10/bd_cb0a_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_11/bd_cb0a_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_12/bd_cb0a_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_13/bd_cb0a_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_14/bd_cb0a_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_15/bd_cb0a_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_16/bd_cb0a_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_20/bd_cb0a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_21/bd_cb0a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_22/bd_cb0a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_23/bd_cb0a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_24/bd_cb0a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_25/bd_cb0a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_26/bd_cb0a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_27/bd_cb0a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_28/bd_cb0a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_29/bd_cb0a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_30/bd_cb0a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_31/bd_cb0a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_33/bd_cb0a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_34/bd_cb0a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_35/bd_cb0a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_36/bd_cb0a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_37/bd_cb0a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_38/bd_cb0a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_40/bd_cb0a_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_41/bd_cb0a_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_42/bd_cb0a_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_43/bd_cb0a_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_44/bd_cb0a_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_45/bd_cb0a_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_47/bd_cb0a_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_48/bd_cb0a_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_49/bd_cb0a_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_50/bd_cb0a_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_51/bd_cb0a_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_52/bd_cb0a_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_54/bd_cb0a_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_55/bd_cb0a_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_56/bd_cb0a_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_57/bd_cb0a_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_58/bd_cb0a_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_59/bd_cb0a_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_61/bd_cb0a_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_62/bd_cb0a_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_63/bd_cb0a_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_64/bd_cb0a_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_65/bd_cb0a_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_66/bd_cb0a_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_68/bd_cb0a_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_69/bd_cb0a_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_70/bd_cb0a_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_71/bd_cb0a_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_72/bd_cb0a_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_73/bd_cb0a_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_75/bd_cb0a_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_76/bd_cb0a_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_77/bd_cb0a_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_78/bd_cb0a_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_79/bd_cb0a_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_80/bd_cb0a_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_82/bd_cb0a_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_83/bd_cb0a_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_84/bd_cb0a_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_85/bd_cb0a_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_86/bd_cb0a_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_87/bd_cb0a_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_89/bd_cb0a_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_90/bd_cb0a_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_91/bd_cb0a_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_92/bd_cb0a_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_93/bd_cb0a_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_94/bd_cb0a_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_96/bd_cb0a_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_97/bd_cb0a_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_98/bd_cb0a_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_99/bd_cb0a_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_100/bd_cb0a_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/bd_0/ip/ip_101/bd_cb0a_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_gpio_0_0/SoC_EV_BD_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_gpio_0_0/SoC_EV_BD_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_iic_0_0/SoC_EV_BD_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_axi_iic_0_0/SoC_EV_BD_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/SoC_EV_BD_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.gen/sources_1/bd/SoC_EV_BD/ip/SoC_EV_BD_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.srcs/constrs_1/imports/basys_datasheet/Basys-3-Master.xdc
set_property used_in_implementation false [get_files /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.srcs/constrs_1/imports/basys_datasheet/Basys-3-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/wonhyeok/SoC_EV_IPmodule/SoC_EV_IPmodule.srcs/utils_1/imports/synth_1/button_cntr.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top SoC_EV_BD_wrapper -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SoC_EV_BD_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file SoC_EV_BD_wrapper_utilization_synth.rpt -pb SoC_EV_BD_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
